// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuBdF_IOmL0Lbn85PFE7GwK3Zm_5Nd7lA',
    appId: '1:609886338719:web:dfe8c0b55ea25b2275ecaa',
    messagingSenderId: '609886338719',
    projectId: 'produit-cosmetique',
    authDomain: 'produit-cosmetique.firebaseapp.com',
    storageBucket: 'produit-cosmetique.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtA8kqeT_ZbIy93pb2bJiligMSXBmvUa0',
    appId: '1:609886338719:android:47ae67d839f9fa3775ecaa',
    messagingSenderId: '609886338719',
    projectId: 'produit-cosmetique',
    storageBucket: 'produit-cosmetique.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS_s07k-8NJNKlFicykV2wydN2aFpsDJI',
    appId: '1:609886338719:ios:d43df8ce07deed3075ecaa',
    messagingSenderId: '609886338719',
    projectId: 'produit-cosmetique',
    storageBucket: 'produit-cosmetique.appspot.com',
    iosBundleId: 'com.example.projetFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS_s07k-8NJNKlFicykV2wydN2aFpsDJI',
    appId: '1:609886338719:ios:ad271ca65e14d23675ecaa',
    messagingSenderId: '609886338719',
    projectId: 'produit-cosmetique',
    storageBucket: 'produit-cosmetique.appspot.com',
    iosBundleId: 'com.example.projetFlutter.RunnerTests',
  );
}
